# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'crliving' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for crliving

  target 'crlivingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'crlivingUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'Masonry', '~> 1.0.2'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'MJExtension', '~> 3.0.13'
  pod 'LFLiveKit', '~> 2.5'
  pod 'YYKit', '~> 1.0.9'

end
